steps:
- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: "Rodando composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

- id: "Rodando docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
  args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']
